services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: compis_mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGODB_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - compis_network

  api:
    build: .
    container_name: compis_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - PORT=8080
    depends_on:
      - mongodb
    networks:
      - compis_network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  compis_network:
    driver: bridge