version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: compis_mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - compis_network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  compis_network:
    driver: bridge