version: "3.8"

services:
  nginx-loadbalancer:
    build: .
    container_name: nginx-loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
